### ISSUE TITLE
✨ [Feature] 영화 목록 페이지 작성

### ISSUE THREAD

**Issue by joonho0410** [42JJHypertube/42_hypertube#15]
### Description

메인 페이지에서 영화목록을 확인할 수 있도록 만듭니다.

### Todo

- [ ] 메인에서 영화 이름, 포스터를 확인 할 수 있도록만듬
- [ ] loading component 작성
- [ ] 무한 스크롤 구현
