### ISSUE TITLE
✨ [Feature] 영화소개 Detail 페이지 작성

### ISSUE THREAD

**Issue by joonho0410** [42JJHypertube/42_hypertube#38]
### Description

영화 소개 및 시청을 위한 Detail 페이지를 작성합니다.

### Todo

- [ ] 영화 소개를 위한 Detail 페이지 작성
- [ ] 영화 포스터 게시
- [ ] 영화에 대한 평점 및 배우, 출연진등 상세 Detail 게시
- [ ] HyperTube의 자체 코멘트 기능 게시
