### ISSUE TITLE
[TODO] 프론트 해야하는 작업들

### ISSUE THREAD

**Issue by joonho0410** [42JJHypertube/42_hypertube#42]
> ### ISSUE
> * Type: `feature`, `fix`, `test`
> * Detail: fix actions from client redux
> 
 ### TODO
1. [ ]  프론트 소켓만들기
2. [ ]  YTS 사이트에서 토렌트 긁어오기
3. [ ]  플레이어 만들기 ( 화질변경, 음량수정, 시간이동 등등..)
4. [ ]  자막 사이트 긁어오기 
5. [ ]
