### ISSUE TITLE
✨ [Feature] 메인 Navigation bar 개선

### ISSUE THREAD

**Issue by greatSweetMango** [42JJHypertube/42_hypertube#43]
### Description

메인페이지 Nav Bar를 개선합니다.

### Todo

- [ ] Nav bar 스타일 개선
- [ ] Search에 빈문자열 검색시 404페이지
- [ ] 유저 이미지 클릭시 내정보 페이지 이동

### ETC

https://github.com/42JJHypertube/42_hypertube/issues/29
