### ISSUE TITLE
✨ [Feature] 자막기능 API 구현

### ISSUE THREAD

**Issue by greatSweetMango** [42JJHypertube/42_hypertube#64]
### Description

자막을 다운받아 클라이언트에 제공합니다.

### Todo

- [x] 현재 다운받은 자막파일들을 저장하고 위해 자막 테이블 추가
- [x] OpenSubtitles API에서 자막 가져오기
- [x] 자막 제공 API 작성
