### ISSUE TITLE
🔨 [Refactoring] 소켓 최적화

### ISSUE THREAD

**Issue by joonho0410** [42JJHypertube/42_hypertube#69]
### Description

- Observer Pattern을 사용해서 현재 다운로드 상태를 관리하는 소켓을 리팩토링합니다.

### Todo

- [x] 서버 소켓 수정
- [x] 브로커 클래스 생성
- [x] 다운로드 컴포넌트 수정
