### ISSUE TITLE
✨ [Feature]  메인화면 장르별 화면 구성

### ISSUE THREAD

**Issue by joonho0410** [42JJHypertube/42_hypertube#71]
### Description

메인 화면에 TopRated, NowPlaying, UpComing등 다양한 영화의 정보를 보여줄 수 있도록 합니다.

### Todo

- [x] 각 종류에 맞는 데이터를 보여줄 수 있는 Section 컴포넌트작성
- [x] Section에서 Focus 및, 좌우 클릭 혹은 드래그를 통해서 스크롤 기능
- [x] 슬라이더를 원통형으로 순환할 수 있게 보여주기
- [x] 화면크기에 따른 CSS 조정.
- [ ] 스켈레톤을 통해서, 비 로딩시에도 보여줄 화면 작성.
- [ ] 화면 갯수가 바뀌었을때 현재 Index를 고정할 수 있도록하기
- [ ] 메인 섹션 작성
